version: '3.3'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=university
    volumes:
    - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
  backend:
    image: lyyych/k3s-task2-server:latest
    environment:
      - DB_USERS_HOST=localhost
      - DB_USERS_PORT=27017
    ports:
      - 8080:8080
    container_name: server
    depends_on:
      - mongodb
    networks:
      - university-network

networks:
  university-network:
    name: university-network