version: '3.3'

services:
  db:
    image: lyyych/transactions-db:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - university-network
  backend:
    image: lyyych/transactions-backend:latest
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SSL_MODE=${SSL_MODE}
    ports:
      - ${SERVER_ENDPOINT}:8080
    container_name: backend
    depends_on:
      - db
    networks:
      - university-network

networks:
  university-network:
    name: university-network