version: '3.3'

services:
  mongo:
    image: lyyych/k3s-task2-db:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=university
    ports:
      - 27017:27017
    networks:
      - university-network
  redis:
    image: redis:latest
    ports:
    - 6379:6379
    networks:
      - university-network
#  backend:
#    build: .
#    ports:
#      - 8080:8080
#    container_name: server
#    depends_on:
#      - mongo
#      - redis
#    networks:
#      - university-network

networks:
  university-network:
    name: university-network