version: '3.3'

services:
  db:
    image: lyyych/transactions-db:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    ports:
      - ${TEST_DB_PORT}:5432
    networks:
      - university-network
  backend:
    image: lyyych/transactions-backend:latest
    restart: always
    environment:
      - DB_HOST=${TEST_DB_HOST}
      - DB_PORT=${TEST_DB_PORT}
      - DB_USER=${TEST_DB_USER}
      - DB_NAME=${TEST_DB_NAME}
      - DB_PASSWORD=${TEST_DB_PASSWORD}
      - SSL_MODE=${TEST_SSL_MODE}
    ports:
      - ${TEST_SERVER_ENDPOINT}:8080
    container_name: backend
    depends_on:
      - db
    networks:
      - university-network

networks:
  university-network:
    name: university-network