apiVersion: apps/v1
kind: Deployment
metadata:
  name: university-api
  labels:
    app: university-api
spec:
  selector:
    matchLabels:
      project: university-api     
  replicas: 1
  template:
    metadata:
      labels:
        project: university-api
    spec:
      containers:
      - name: server
        image: lyyych/deployments-task2-server
        ports:
        - containerPort: 8080
      - name: db
        image: lyyych/deployments-task2-db
        env:
          - name: MONGO_INITDB_DATABASE
            value: university
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: university-service
  labels:
    name: university-service
spec:
  selector:
    project: university-api
  ports:
    - name: listener
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
